name: Fetch Download Shield

on:
  schedule:
    # This cron runs at 18:30 UTC which corresponds to 00:00 IST (UTC+5:30)
    - cron: '30 18 * * *'
  push:
    paths:
      - ".github/workflows/downloads.yml"

jobs:
  fetch-shield:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch shield image
        run: |
          curl -o .assets/downloads.svg https://img.shields.io/pypi/dm/flix-cli

      - name: Commit and push if updated
        run: |
          git config user.name 'Detective Douche'
          git config user.email 'guacamole@demonkingswarn.live'
          git add .assets/downloads.svg
          git diff --cached --quiet || (git commit -m 'Update download shield' && git push)


